// Generated by Wrangler by running `wrangler types`

interface Env {
    COMMANDS: KVNamespace;
    DISCORD_TOKEN: string;
    DISCORD_PUBLIC_KEY: string;
    DISCORD_APP_ID: string;
    DISCORD_APP_OWNER_ID: string;
}
