#:schema node_modules/wrangler/config-schema.json
name = "blacksmith-dev"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "COMMANDS"
id = "18078eb6be0a4ac8867b306bd45f8250"

[env.production]
name = "blacksmith"

[[env.production.kv_namespaces]]
binding = "COMMANDS"
id = "f52b37004eb54802881aa3c2a9ee04b4"
