site_name: Blacksmith
site_description: Cloudflare Workers-based bot for adding custom slash commands to a server.
repo_url: https://github.com/nint8835/blacksmith
repo_name: nint8835/blacksmith
edit_uri: edit/master/site/docs/
theme:
  name: material
  palette:
    primary: deep purple
    accent: yellow
    scheme: slate
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/message-processing
    repo: fontawesome/brands/github
  features:
    - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bootlegjohn
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/nint8835/blacksmith
      name: Source Code
copyright: Copyright &copy; 2021 Riley Flynn
plugins:
  - git-revision-date-localized
markdown_extensions:
  - attr_list
